name: Deploy to Dev - WEB

on:
  push:
    branches:
      - dev

  workflow_dispatch:

env:
  AWS_REGION: ${{ secrets.AWS_REGION }}

permissions:
  contents: read

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]

    environment: dev

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: actions/setup-node@v2
        with:
          node-version: ${{matrix.node-version}}

      - name: Cache node modules
        uses: actions/cache@v3
        id: npm_cache_id
        with:
          path: node_modules
          key: ${{ runner.os }}-DEV-npm-cache-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-DEV-npm-cache-
            ${{ runner.os }}-DEV-

      - name: Install Dependencies
        if: steps.npm_cache_id.outputs.cache-hit != 'true'
        run: npm ci

      - name: build app
        run: npm run build --if-present
        env:
          CI: ""

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          aws-access-key-id: ${{ secrets.AWS_DEV_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_DEV_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Upload to S3
        run: aws s3 sync ./build s3://wayleave-web-frontend-dev

      - name: invalidate cache
        run: aws cloudfront create-invalidation --distribution-id ${{ secrets.DEV_CF_DISTRIBUTION_ID }} --paths "/*"
